import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { DataServiceService } from 'src/app/Data/data-service.service';
import { Observable } from 'rxjs';
import { map } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class EnquiryService extends DataServiceService {

  constructor(public http :HttpClient) { super(http); }
  public objEnquiry :any={
    "EnquiryNo" : "0",
    "EnquiryDt" : "",
    "branch" : "0",
    //"Branchname" : "",
    "SalesManCode" : "0",
    //"SMname" : "",
    "typecode" : "0",
    //"TYPENAME" : "",
    "PayTypeCOde" : "",
    "SourceCode" : "0",
    "sub_Source_code" : "0",
    // "EXPBOOKDT" : "",
    // "TestDrive" : "",
    "Response" : "",
    // "CLOSED" : "",
    // "SINVNO" : "0",
    // "ACNO" : "0",
    // "sinvdt" : "",
    "INSTITUTECODE" : "",
    "ItemCode" : "",
    //"ItemName" : "",
    "OPTPASSENGER" : "",
    "OPTPASSANGERD" : "",
    "OPTGOODS" : "",
    "OPTGOODSD" : "",
    "finapply" : "",
    "HpaCode" : "0",
    "VisitorName" : "",
    "QuotNo" : "0",
    // "exchgconstant" : "",
    // "exchgModel" : "",
    // "Exchgpurdt" : "",
    // "ExchgModelRemark" : "",
    // "ExchgRTONo" : "",
    // "ExchgExpPrice" : "0",
    // "ExchgOfferPrice" : "0",
    // "proposalno" : "0",
    // "proposaldt" : "",
    // "bookingamt" : "0",
    "profilecode" : "0",
    "ownerProfile" : "",
    "WITHACCES" : "",
    "WITHMETER" : "",
    "FirstName" : "",
    "MiddleName" : "",
    "LastName" : "",
    // "LoanAmt" : "0",
    // "Balance" : "0",
    // "FileCharge" : "0",
    // "DownPayment" : "0",
    // "RateOfInt" : "0",
    // "LoanMonths" : "0",
    // "LoanMonths1Final" : "0",
    // "Installments3" : "0",
    // "AddAmount1" : "0",
    // "AddAmount2" : "0",
    // "AddAmount3" : "0",
    // "LaonTot1" : "0",
    // "LaonTot2" : "0",
    // "LaonTot3" : "0",
    // "BankBranch" : "",
    // "AgentYN" : "",
    // "ADDTYPE" : "",
    // // "BIRTHDATE" : "",
    // "Add1" : "",
    // "Add2" : "",
    // "Add3" : "",
    // "AREACD" : "0",
    // "AREA" : "",
    // "CITY" : "",
    // "Pin" : "",
    // "Mobile" : "",
    // "Email" : "",
    // "ADHARNO" : "",
    // "PANNO" : "",
    // "LICENCENO" : "",
    // "ElectionCard" : "",
    // "statecd" : "0",
    // "state" : "",
    // "AddressType" : "0",
    // "BillingAddress" : "",
    // "Mobile2" : "",
    // "Mobile3" : "",
    // "basicvalue" : "0",
    // "CrTemp" : "0",
    // "srto" : "0",
    // "sHPACharge" : "0",
    // "sinsurance" : "0",
    // "sLifetimeTax" : "0",
    // "smeterflag" : "0",
    // "saccessories" : "0",
    // "sGRANDTOTAL" : "0",
    // "BasicValueQuot" : "0",
    // "QuotDt" : "0",
    // "CRtempQuot" : "0",
    // "RTOQuot" : "0",
    // "HPAQuot" : "0",
    // "InsuranceQuot" : "0",
    // "LifetimeTaxQuot" : "0",
    // "MeterFlagQuot" : "0",
    // "AccessoriesQuot" : "0",
    // "GrandTotQuot" : "0",

  }

  public resetService() {
    this.objEnquiry = {
      "EnquiryNo" : "0",
      "EnquiryDt" : "",
      "branch" : "0",
      // "Branchname" : "",
      "SalesManCode" : "0",
      //"SMname" : "",
      "typecode" : "0",
      // "TYPENAME" : "",
      "PayTypeCOde" : "",
      "SourceCode" : "0",
      "sub_Source_code" : "0",
      // "EXPBOOKDT" : "",
      // "TestDrive" : "",
      "Response" : "",
      // "CLOSED" : "",
      // "SINVNO" : "0",
      // "ACNO" : "0",
      // "sinvdt" : "",
      "INSTITUTECODE" : "",
      "ItemCode" : "",
      // "ItemName" : "",
      "OPTPASSENGER" : "",
      "OPTPASSANGERD" : "",
      "OPTGOODS" : "",
      "OPTGOODSD" : "",
      "finapply" : "",
      "HpaCode" : "0",
      "VisitorName" : "",
      "QuotNo" : "0",
      // "exchgconstant" : "",
      // "exchgModel" : "",
      // "Exchgpurdt" : "",
      // "ExchgModelRemark" : "",
      // "ExchgRTONo" : "",
      // "ExchgExpPrice" : "0",
      // "ExchgOfferPrice" : "0",
      // "proposalno" : "0",
      // "proposaldt" : "",
      // "bookingamt" : "0",
      "profilecode" : "0",
      "ownerProfile" : "",
      "WITHACCES" : "",
      "WITHMETER" : "",
      "FirstName" : "",
      "MiddleName" : "",
      "LastName" : "",
      // "LoanAmt" : "0",
      // "Balance" : "0",
      // "FileCharge" : "0",
      // "DownPayment" : "0",
      // "RateOfInt" : "0",
      // "LoanMonths" : "0",
      // "LoanMonths1Final" : "0",
      // "Installments3" : "0",
      // "AddAmount1" : "0",
      // "AddAmount2" : "0",
      // "AddAmount3" : "0",
      // "LaonTot1" : "0",
      // "LaonTot2" : "0",
      // "LaonTot3" : "0",
      // "BankBranch" : "",
      // "AgentYN" : "",
      // "ADDTYPE" : "",
      // // "BIRTHDATE" : "",
      // "Add1" : "",
      // "Add2" : "",
      // "Add3" : "",
      // "AREACD" : "0",
      // "AREA" : "",
      // "CITY" : "",
      // "Pin" : "",
      // "Mobile" : "",
      // "Email" : "",
      // "ADHARNO" : "",
      // "PANNO" : "",
      // "LICENCENO" : "",
      // "ElectionCard" : "",
      // "statecd" : "0",
      // "state" : "",
      // "AddressType" : "0",
      // "BillingAddress" : "",
      // "Mobile2" : "",
      // "Mobile3" : "",
      // "basicvalue" : "0",
      // "CrTemp" : "0",
      // "srto" : "0",
      // "sHPACharge" : "0",
      // "sinsurance" : "0",
      // "sLifetimeTax" : "0",
      // "smeterflag" : "0",
      // "saccessories" : "0",
      // "sGRANDTOTAL" : "0",
      // "BasicValueQuot" : "0",
      // "QuotDt" : "0",
      // "CRtempQuot" : "0",
      // "RTOQuot" : "0",
      // "HPAQuot" : "0",
      // "InsuranceQuot" : "0",
      // "LifetimeTaxQuot" : "0",
      // "MeterFlagQuot" : "0",
      // "AccessoriesQuot" : "0",
      // "GrandTotQuot" : "0",
    }}
    getEnquiry(data:any): Observable<any> {
      debugger
      var param = { "EnquiryNo": data };
      return this.post("Enquiry/getEnquiry", param).pipe(map(
        (res: any) => {
          debugger
          return res
        }
      ));
    }
      
  public insertEnquiry(data:any): Observable<any> {
    debugger
    return this.post("Enquiry/insertEnquiry", data).pipe(map(
      (res: any) => {
        return res;
      }
    ));
  }
}
