import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { DataServiceService } from 'src/app/Data/data-service.service';
import { Observable } from 'rxjs';
import { map } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class DelivryorderService extends DataServiceService {

  constructor(public http : HttpClient) { super(http); }
  public objDeliveryOrder :any ={
    "DONo" : "0",
    "ReceiptNo" : "",
    "DoDate" : "",
    "VehicleCode" : "",
    // "Invno" : "0",
    "qty" : "0",
    "AllotDt":"",
    "PRODCODE" : "",
    "ChasisNo" : "",
    "EngineNo" : "",
    "ColorCode" : "0",
    "ColorName" : "",
    "ACNO" : "0",
    //"ACNAME" : "",
    "SALEPRICE" : "0",
    "ACBAL" : "0",
     // "CLBAL":"0",
    "LocationCode" : "0",
    "HpaCode" : "0",
    //"HPAYN": "",
    "TANKNO" : "",
    "gaskitno" : "",
    "CYLINSTALDT" : "",
    "REMARK" : "",
    "KEYNO" : "",
    // "ItemName" : "",
    "BODYTYPE" : "",
    "PROFILECODE" : "0",
    "WITHACCES" : "",
    "withaccessyn" : "0",
    "WITHMETER" : "",
    "withmeteryn" : "0",
    "USERID" : "",
    // "ENTDATE" : "",
    "BOOKINGDISCOUNT" : "0",
    "AgentCode" : "0",
    "SmCode" : "0",
    "BranchCOde" : "0",
    "PROPOSALNO" : "0",
    "SItemInv" : "",
    "sBasicValue" : "0",
    "sBodyKit" : "0",
    "sTaxableAmt" : "0",
    "CGST" : "0",
    "SGST" : "0",
    "GSTCESS" : "0",
    "sTotinvamt" : "0",
    "sinsurance" : "0",
    "sHPACharge" : "0",
    "MTOKENCHG" : "0",
    "SLIFETIMETAX" : "0",
    "SNOPLATECHG" : "0",
    "sCrTemp" : "0",
    "RTOR": "0",
    "srto" : "0",
    "sHandlingCharge" : "0",
    "SEXTWARANTY" : "0",
    "sInvAmt" : "0",
    "sBasicDiscount" : "0",
    "sOtherCharge1":"0",
    "sGRANDTOTAL" : "0",
    "NGRANDTOTAL" : "0",
    "saccessories" : "0",
    "sMeterFlag" : "0",
    "ACCESDB" : "0",
    "ACEESCD" : "0",
    "ACCESSINV" : "",
    "ACCESGSTCD" : "0",
    "ACCESCGSTR" : "0",
    "ACCESSGSTR" : "0",
    "METERDB" : "0",
    "METERCD" : "0",
    "METERINV" : "",
    "METERGSTCD" : "0",
    "METERCGSTR" : "0",
    "METERSGSTR" : "0",
    "ACCESMETER" : "0",
    "GSTCD" : "0",
    "CGSTR" : "0",
    "SGSTR" : "0",
    "GSTCESSR" : "0",
    "IGSTR" : "0",
    "CashDiscount" : "0",
    "HCGSTA" : "0",
    "HSGSTA" : "0",
    "HANDLINGGSTNET" : "0",
    "HSNCODE" : "",
    "sProposalDiscount" : "0",
    "BODYHSNNO" : "",
    "ACCESHSNNO" : "",
    "METERHSNNO" : "",
    "AgentEnqNo" : "0",
    "METERCODE" : "0",
    "MeterSrno" : "",
    "BatteryNo" : "",
    "BOOKINLOCATION" : "0",
    "zBroker" : "0",
    "stockyn" : "",
    "bookingdiscno" : "0",
    "NewYearStart" : "",
    "dbname" : "",
  }
  public resetService(){
    this.objDeliveryOrder = {
      "DONo" : "0",
      "ReceiptNo" : "",
      "DoDate" : "",
      "VehicleCode" : "",
      //"Invno" : "0",
      "qty" : "0",
      "AllotDt" : "",
      "PRODCODE" : "",
      "ChasisNo" : "",
      "EngineNo" : "",
      "ColorCode" : "0",
      "ColorName" : "",
      "ACNO" : "0",
      //"ACNAME" : "",
      //"ItemName" : "",
      "SALEPRICE" : "0",
      "ACBAL" : "0",
      //"CLBAL" :"0",
      "LocationCode" : "0",
      "HpaCode" : "0",
      //"HPAYN": "",
      "TANKNO" : "",
      "gaskitno" : "",
      "CYLINSTALDT" : "",
      "REMARK" : "",
      "KEYNO" : "",
      "BODYTYPE" : "",
      "PROFILECODE" : "0",
      "WITHACCES" : "",
      "withaccessyn" : "0",
      "WITHMETER" : "",
      "withmeteryn" : "0",
      "USERID" : "",
      // "ENTDATE" : "",
      "BOOKINGDISCOUNT" : "0",
      "AgentCode" : "0",
      "SmCode" : "0",
      "BranchCOde" : "0",
      "PROPOSALNO" : "0",
      "SItemInv" : "",
      "sBasicValue" : "0",
      "sBodyKit" : "0",
      "sTaxableAmt" : "0",
      "CGST" : "0",
      "SGST" : "0",
      "GSTCESS" : "0",
      "sTotinvamt" : "0",
      "sinsurance" : "0",
      "sHPACharge" : "0",
      "MTOKENCHG" : "0",
      "SLIFETIMETAX" : "0",
      "SNOPLATECHG" : "0",
      "sCrTemp" : "0",
      //"RTOR": "0",
      "srto" : "0",
      "sHandlingCharge" : "0",
      "SEXTWARANTY" : "0",
      "sInvAmt" : "0",
      "sBasicDiscount" : "0",
      "sOtherCharge1":"0",
      "sGRANDTOTAL" : "0",
      "NGRANDTOTAL" : "0",
      "saccessories" : "0",
      "sMeterFlag" : "0",
      "ACCESDB" : "0",
      "ACEESCD" : "0",
      "ACCESSINV" : "",
      "ACCESGSTCD" : "0",
      "ACCESCGSTR" : "0",
      "ACCESSGSTR" : "0",
      "METERDB" : "0",
      "METERCD" : "0",
      "METERINV" : "",
      "METERGSTCD" : "0",
      "METERCGSTR" : "0",
      "METERSGSTR" : "0",
      "ACCESMETER" : "0",
      "GSTCD" : "0",
      "CGSTR" : "0",
      "SGSTR" : "0",
      "GSTCESSR" : "0",
      "IGSTR" : "0",
      "CashDiscount" : "0",
      "HCGSTA" : "0",
      "HSGSTA" : "0",
      "HANDLINGGSTNET" : "0",
      "HSNCODE" : "",
      "sProposalDiscount" : "0",
      "BODYHSNNO" : "",
      "ACCESHSNNO" : "",
      "METERHSNNO" : "",
      "AgentEnqNo" : "0",
      "METERCODE" : "0",
      "MeterSrno" : "",
      "BatteryNo" : "",
      "BOOKINLOCATION" : "0",
      "zBroker" : "0",
      "stockyn" : "",
      "bookingdiscno" : "0",
      "NewYearStart" : "",
      "dbname" : "",
    }
  }
  getdo(data:any): Observable<any> {
    debugger
    var param = { "DONo": data };
    return this.post("Do/getdo", param).pipe(map(
      (res: any) => {
        debugger
        return res
      }
    ));
  }

  
  public insertDo(data:any): Observable<any> {
    debugger
    return this.post("Do/insertDo", data).pipe(map(
      (res: any) => {
        return res;
      }
    ));
  }
}
