import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { DataServiceService } from 'src/app/Data/data-service.service';
import { Observable } from 'rxjs';
import { map } from 'rxjs';


@Injectable({
  providedIn: 'root'
})
export class RetailinvoiceService extends DataServiceService{

  constructor(public http: HttpClient) {super(http); }
  public objRetailInvoice : any ={
    "GJNO" : "",
    "sInvno" : "0",
    "sInvDt" : "0",
    "sSaleDt" : "0",
    "sDBCODE" : "0",
    "DONO" : "0",
    "SItemInv" : "",
    "ProposalSrno" : "0",
    "ACNO" : "0",
    "sReceiptNo" : "",
    "FINANCECODE" : "0",
    "hpayn" : "",
    "sHPloanamount" : "0",
    "LOCATION" : "0",
    "BranchCode" : "0",
    "PROFILECODE" : "0",
    "Skimcode" : "0",
    "sNAR2" : "",
    "sMeterSrNo" : "",
    "BatteryNo" : "",
    "sSchemeAmt" : "0",
    "INQNO" : "0",
    "rtopaidamt" : "0",
    "INSPAID" : "0",
    "TopayRtO" : "0",
    "rtopaidno" : "",
    "rtoremark" : "",
    "RATE" : "0",
    "FREEACCESSORIES" : "",
    "sBasicValue" : "0",
    "sBodyKit" : "0",
    "sTaxableAmt" : "0",
    "CGST" : "0",
    "SGST" : "0",
    "GSTCESS" : "0",
    "sTotinvamt" : "0",
    "sinsurance" : "0",
    "sHPACharge" : "0",
    "MTOKENCHG" : "0",
    "SLIFETIMETAX" : "0",
    "SNOPLATECHG" : "0",
    "sCrTemp" : "0",
    "srto" : "0",
    "sHandlingCharge" : "0",
    "SEXTWARANTY" : "0",
    "sInvAmt" : "0",
    "sBasicDiscount" : "0",
    "sOtherCharge1" : "0",
    "sGRANDTOTAL" : "0",
    "NGRANDTOTAL" : "0",
    "saccessories" : "0",
    "sMeterFlag" : "0",
    "ACCESDB" : "0",
    "ACEESCD" : "0",
    "ACCESSINV" : "",
    "ACCESGSTCD" : "0",
    "ACCESCGSTR" : "0",
    "ACCESSGSTR" : "0",
    "METERDB" : "0",
    "METERCD" : "0",
    "METERINV" : "",
    "METERGSTCD" : "0",
    "METERCGSTR" : "0",
    "ACCESMETER" : "0",
    "GSTCD" : "0",
    "CGSTR" : "0",
    "SGSTR" : "0",
    "GSTCESSR" : "0",
    "IGSTR" : "0",
    "CashDiscount" : "0",
    "HCGSTA" : "0",
    "HSGSTA" : "0",
    "HANDLINGGSTNET" : "0",
    "HSNCODE" : "",
    "sProposalDiscount" : "0",
    "BODYHSNNO" : "",
    "bookingdiscno" : "",
    "ACCESHSNNO" : "",
    "MtaxToPayAmt" : "0",
    "METERHSNNO" : "",
    "IRNno" : "",
    "AcknoledgeNo" : "",
    "AcknoledgeDT" : "0",
    "ITM" : "",
    "CHASISNO" : "0",
    "inscocode" : "0",
    "insdt" : "0",
    "inspaidchno" : "",
    "inspaidchdt" : "0",
    "insuracno" : "0",
    "Acname" : "",
    "ItemName": "",
    "GRP" : "0",
    "SGRP" : "0",
    "SSGRP" : "0",
    "VEHICLECODE" : "",
    "AgentCode" : "0",
    "Dbcode" : "0",
    "add1" : "",
    "add2" : "",
    "add3" : "",
    "area" : "",
    "AREACD" : "0",
    "city" : "",
    "pin" : "0",
    "pho1" : "",
    "mobile" : "",
    "passing" : "",
    "vatcd" : "0",
    "BOOKINGDISCOUNT" : "0",
    "zHPAwith" : "",
    "NAR1" : "",
    "NAR2" : "",
    "NAR3" : "",
    "EntDate" : "0",
    "UserId" : "",
    "BranchId" : "",
    "BranchCD" : "0",
    "DOTNET" : "",
    "hType" : "",
    "JVDOCNO" : "",
    "ENGINENO" : "",
    "DOdt" : "0",
    "WSACNO" : "0",
  }
  public resetService(){
    this.objRetailInvoice={
      "GJNO" : "",
      "sInvno" : "0",
      "sInvDt" : "0",
      "sSaleDt" : "0",
      "ACNAME" : "",
      "sDBCODE" : "0",
      "DONO" : "0",
      "SItemInv" : "",
      "ProposalSrno" : "0",
      "ACNO" : "0",
      "sReceiptNo" : "",
      "ProdCode" : "",
      "FINANCECODE" : "0",
      "hpayn" : "",
      "sHPloanamount" : "0",
      "LOCATION" : "0",
      "BranchCode" : "0",
      "PROFILECODE" : "0",
      "Skimcode" : "0",
      "sNAR2" : "",
      "sMeterSrNo" : "",
      "BatteryNo" : "",
      "sSchemeAmt" : "0",
      "INQNO" : "0",
      "rtopaidamt" : "0",
      "INSPAID" : "0",
      "TopayRtO" : "0",
      "rtopaidno" : "",
      "rtoremark" : "",
      "RATE" : "0",
      "FREEACCESSORIES" : "",
      "sBasicValue" : "0",
      "sBodyKit" : "0",
      "sTaxableAmt" : "0",
      "CGST" : "0",
      "SGST" : "0",
      "GSTCESS" : "0",
      "sTotinvamt" : "0",
      "sinsurance" : "0",
      "sHPACharge" : "0",
      "MTOKENCHG" : "0",
      "SLIFETIMETAX" : "0",
      "SNOPLATECHG" : "0",
      "sCrTemp" : "0",
      "srto" : "0",
      "sHandlingCharge" : "0",
      "SEXTWARANTY" : "0",
      "sInvAmt" : "0",
      "sBasicDiscount" : "0",
      "sOtherCharge1" : "0",
      "sGRANDTOTAL" : "0",
      "NGRANDTOTAL" : "0",
      "saccessories" : "0",
      "sMeterFlag" : "0",
      "ACCESDB" : "0",
      "ACEESCD" : "0",
      "ACCESSINV" : "",
      "ACCESGSTCD" : "0",
      "ACCESCGSTR" : "0",
      "ACCESSGSTR" : "0",
      "METERDB" : "0",
      "METERCD" : "0",
      "METERINV" : "",
      "METERGSTCD" : "0",
      "METERCGSTR" : "0",
      "ACCESMETER" : "0",
      "GSTCD" : "0",
      "CGSTR" : "0",
      "SGSTR" : "0",
      "GSTCESSR" : "0",
      "IGSTR" : "0",
      "CashDiscount" : "0",
      "HCGSTA" : "0",
      "HSGSTA" : "0",
      "HANDLINGGSTNET" : "0",
      "HSNCODE" : "",
      "sProposalDiscount" : "0",
      "BODYHSNNO" : "",
      "bookingdiscno" : "",
      "ACCESHSNNO" : "",
      "MtaxToPayAmt" : "0",
      "METERHSNNO" : "",
      "IRNno" : "",
      "AcknoledgeNo" : "",
      "AcknoledgeDT" : "0",
      "ITM" : "",
      "CHASISNO" : "0",
      "inscocode" : "0",
      "insdt" : "0",
      "inspaidchno" : "",
      "inspaidchdt" : "0",
      "insuracno" : "0",
      "Acname" : "",
      
      "GRP" : "0",
      "SGRP" : "0",
      "SSGRP" : "0",
      "VEHICLECODE" : "",
      "AgentCode" : "0",
      "Dbcode" : "0",
      "add1" : "",
      "add2" : "",
      "add3" : "",
      "area" : "",
      "AREACD" : "0",
      "city" : "",
      "pin" : "0",
      "pho1" : "",
      "mobile" : "",
      "passing" : "",
      "vatcd" : "0",
      "BOOKINGDISCOUNT" : "0",
      "zHPAwith" : "",
      "NAR1" : "",
      "NAR2" : "",
      "NAR3" : "",
      "EntDate" : "0",
      "UserId" : "",
      "BranchId" : "",
      "BranchCD" : "0",
      "DOTNET" : "",
      "hType" : "",
      "JVDOCNO" : "",
      "ENGINENO" : "",
      "DOdt" : "0",
      "WSACNO" : "0",
    }
  }
  getInvoice(data:any): Observable<any> {
    debugger
    var param = { "sInvno": data };
    return this.post("Invoice/getInvoice", param).pipe(map(
      (res: any) => {
        debugger
        return res
      }
    ));
  }

  
  public insertINVOICE(data:any): Observable<any> {
    debugger
    return this.post("Invoice/insertINVOICE", data).pipe(map(
      (res: any) => {
        return res;
      }
    ));
  }
}
